---
sudo: required
language: python
python: "2.7"

dist: trusty

before_install:
  - env
  - echo '[all]' > hosts
  - |
    for i in 7 6 ; do
      docker run --name centos$i -di centos:$i /sbin/init
      echo centos$i >> hosts
    done

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../:tests/roles' | tee ansible.cfg
  - cat hosts
  - pip install ansible-lint
  - ansible-lint --version

script:
  - ansible-playbook -i localhost, --syntax-check tests/test.yml
  - ansible-lint tests/test.yml
  - ansible-playbook -i hosts tests/test.yml

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
